# Generated by Django 2.2.8 on 2022-10-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonushistorymodel',
            name='bonusamount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bonushistorymodel',
            name='purchasedamount',
            field=models.FloatField(),
        ),
    ]
