# Generated by Django 2.2.8 on 2022-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=32)),
                ('ProductId', models.CharField(max_length=16)),
                ('ProductName', models.CharField(max_length=32)),
                ('Quantity', models.IntegerField()),
                ('CouponCode', models.CharField(blank=True, max_length=62)),
                ('TotalPrice', models.FloatField(max_length=32)),
                ('Sponsor', models.CharField(max_length=32)),
            ],
        ),
    ]
